
#-----------------------------------------------------------------------

APP       := MonitApp
TARGET    := StructDataGetServer
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

# INCLUDE   += -I./jce/
INCLUDE	  += -I/home/tarsjce/MonitApp/tarsCommon/

LIB       += 

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
