App			:= MonitApp
TARGET 	 	:= libConfigHolder.a
CFLAGS  	:= -g
MFLAGS		:= 64
DFLAGS  	:= all
CONFIG 		:= 
STRIP_FLAG  := N
J2CPP_FLAG  := 

INCLUDE 	+=
include 	/usr/local/tars/cpp/makefile/makefile.tars
