
#-----------------------------------------------------------------------

APP       := MonitApp
TARGET    := DBServer
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

#INCLUDE   += -I/home/MonitApp/DBServer/jce/
INCLUDE   += -I/home/MonitApp/StructDataGetServer/
INCLUDE   += -I/home/tarsjce/MonitApp/tarsCommon/
LIB       += -lmysqlclient
LIB		  += -ltarsutil


#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
